apiVersion: v1
entries:
  solr-operator:
  - apiVersion: v1
    appVersion: v0.2.8
    created: "2021-01-11T15:21:23.033109-05:00"
    description: The Solr Operator enables easy management of Solr resources within
      Kubernetes.
    digest: 0aafa7d978f376e368ef4d609e917ba8cd6dc087535e2777479a1b87cd65d9c9
    home: https://github.com/bloomberg/solr-operator
    icon: https://lucene.apache.org/theme/images/solr/identity/Solr_Logo_on_white.png
    keywords:
    - solr
    - apache
    - search
    - lucene
    - operator
    kubeVersion: '>= 1.16.0-0'
    maintainers:
    - email: houston@apache.org
      name: Houston Putman
    - email: bsankaranara@bloomberg.net
      name: Balaji Sankaranarayanan
    name: solr-operator
    sources:
    - https://github.com/bloomberg/solr-operator
    urls:
    - https://github.com/bloomberg/solr-operator/releases/download/v0.2.8/solr-operator-0.2.8.tgz
    version: 0.2.8
  - apiVersion: v1
    appVersion: v0.2.7
    created: "2020-12-14T17:55:28.546801-05:00"
    description: The Solr Operator enables easy management of Solr resources within
      Kubernetes.
    digest: 9627073abdbd7c3ac9a0616f0582e78c6889eea9963b6ef5b38aa1e3370fd433
    home: https://github.com/bloomberg/solr-operator
    icon: https://lucene.apache.org/theme/images/solr/identity/Solr_Logo_on_white.png
    keywords:
    - solr
    - apache
    - search
    - lucene
    - operator
    kubeVersion: '>= 1.13.0-0'
    maintainers:
    - email: houston@apache.org
      name: Houston Putman
    - email: bsankaranara@bloomberg.net
      name: Balaji Sankaranarayanan
    name: solr-operator
    sources:
    - https://github.com/bloomberg/solr-operator
    urls:
    - https://github.com/bloomberg/solr-operator/releases/download/v0.2.7/solr-operator-0.2.7.tgz
    version: 0.2.7
  - apiVersion: v1
    appVersion: v0.2.6
    created: "2020-08-10T15:25:32.770735-04:00"
    description: The Solr Operator enables easy management of Solr resources within
      Kubernetes.
    digest: 15ea4636403cdd7d6a565fc599c67b908f4293c0bff8d1a85dad5bc7c29311df
    home: https://github.com/bloomberg/solr-operator
    icon: https://lucene.apache.org/theme/images/solr/identity/Solr_Logo_on_white.png
    keywords:
    - solr
    - apache
    - search
    - lucene
    - operator
    kubeVersion: '>= 1.13.0-0'
    maintainers:
    - email: houston@apache.org
      name: Houston Putman
    - email: bsankaranara@bloomberg.net
      name: Balaji Sankaranarayanan
    name: solr-operator
    sources:
    - https://github.com/bloomberg/solr-operator
    urls:
    - https://github.com/bloomberg/solr-operator/releases/download/v0.2.6/solr-operator-0.2.6.tgz
    version: 0.2.6
  - apiVersion: v1
    appVersion: v0.2.5
    created: "2020-05-20T12:28:07.211507-04:00"
    description: The Solr Operator enables easy management of Solr resources within
      Kubernetes.
    digest: 8ccc461fbc1ccd6c149fc34b40f049155f41131c03d291bca1f469cddb0c09dd
    home: https://github.com/bloomberg/solr-operator
    icon: https://lucene.apache.org/theme/images/solr/identity/Solr_Logo_on_white.png
    keywords:
    - solr
    - apache
    - search
    - lucene
    - operator
    kubeVersion: '>= 1.13.0-0'
    maintainers:
    - email: houston@apache.org
      name: Houston Putman
    name: solr-operator
    sources:
    - https://github.com/bloomberg/solr-operator
    urls:
    - https://github.com/bloomberg/solr-operator/releases/download/v0.2.5/solr-operator-0.2.5.tgz
    version: 0.2.5
generated: "2021-01-11T15:21:23.028609-05:00"
