apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: etcd-operator
spec:
  replicas: 1
  selector:
    matchLabels:
        name: etcd-operator
  template:
    metadata:
      labels:
        name: etcd-operator
    spec:
      containers:
      - name: etcd-operator
        image: quay.io/coreos/etcd-operator:v0.9.3
        command:
        - etcd-operator
        - -cluster-wide
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zookeeperclusters.zookeeper.pravega.io
spec:
  group: zookeeper.pravega.io
  names:
    kind: ZookeeperCluster
    listKind: ZookeeperClusterList
    plural: zookeeperclusters
    singular: zookeepercluster
    shortNames:
      - zk
  additionalPrinterColumns:
  - name: Members
    type: integer
    description: The number zookeeper members running
    JSONPath: .status.replicas
  - name: Ready Members
    type: integer
    description: The number zookeeper members ready
    JSONPath: .status.readyReplicas
  - name: Internal Endpoint
    type: string
    description: Client endpoint internal to cluster network
    JSONPath: .status.internalClientEndpoint
  - name: External Endpoint
    type: string
    description: Client endpoint external to cluster network via LoadBalancer
    JSONPath: .status.externalClientEndpoint
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  scope: Namespaced
  version: v1beta1
  subresources:
    status: {}

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zk-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zk-operator
  template:
    metadata:
      labels:
        name: zk-operator
    spec:
      serviceAccountName: zookeeper-operator
      containers:
        - name: zk-operator
          # Replace this with the built image name
          image: pravega/zookeeper-operator:v0.2.0
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          command:
          - zookeeper-operator
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
          - name: WATCH_NAMESPACE
            value: ""
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "zk-operator"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zookeeper-operator

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: zookeeper-operator
rules:
- apiGroups:
  - zookeeper.pravega.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: zookeeper-operator-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: zookeeper-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: zookeeper-operator
  apiGroup: rbac.authorization.k8s.io
