apiVersion: solr.apache.org/v1beta1
kind: SolrPrometheusExporter
metadata:
  name: solrprometheusexporter-sample
spec:
  solrReference:
    cloud:
      name: "example"
  numThreads: 4
  image:
    tag: 8.7.0
