apiVersion: solr.bloomberg.com/v1beta1
kind: SolrCloud
metadata:
  name: example-with-tolerations
spec:
  replicas: 1
  solrImage:
    tag: 8.7.0
  customSolrKubeOptions:
    podOptions:
      nodeSelector:
        beta.kubernetes.io/os: linux
        beta.kubernetes.io/arch: amd64
      tolerations:
        - effect: NoSchedule
          key: node-restriction.kubernetes.io/workloads
          operator: Equal
          value: solrclouds
      resources:
        limits:
          memory: "1G"
        requests:
          cpu: "65m"
          memory: "156Mi"
  zookeeperRef:
    provided:
      persistence:
        spec:
          storageClassName: "hostpath"
          resources:
            requests:
              storage: "5Gi"
      replicas: 1
      zookeeperPodPolicy:
        nodeSelector:
          beta.kubernetes.io/os: linux
          beta.kubernetes.io/arch: amd64
        tolerations:
          - effect: NoSchedule
            key: node-restriction.kubernetes.io/workloads
            operator: Equal
            value: zookeeper
        resources:
          limits:
            memory: "1G"
          requests:
            cpu: "65m"
            memory: "156Mi"
