apiVersion: solr.apache.org/v1beta1
kind: SolrBackup
metadata:
  name: solrbackup-test
  namespace: default
spec:
  persistence:
    volume:
      source:
        persistentVolumeClaim:
          claimName: "pvc-test"
  solrCloud: example
  collections:
    - example
