apiVersion: solr.bloomberg.com/v1beta1
kind: SolrPrometheusExporter
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: solrprometheusexporter-sample
spec:
  solrReference:
    cloud:
      name: "example"
  solrImage:
    tag: 8.2.0
