apiVersion: solr.bloomberg.com/v1beta1
kind: SolrPrometheusExporter
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: solrprometheusexporter-sample
spec:
  solrReference:
    standalone:
      address: "http://example-solrcloud-common.default/solr"
  image:
    tag: 8.2.0
