apiVersion: solr.bloomberg.com/v1beta1
kind: SolrCloud
metadata:
  name: example-with-tolerations
spec:
  dataPvcSpec:
    resources:
      requests:
        storage: "5Gi"
  replicas: 1
  solrImage:
    tag: 8.2.0
  solrJavaMem: "-Xms1g -Xmx3g"
  customSolrKubeOptions:
    podOptions:
      nodeSelector:
        beta.kubernetes.io/os: linux
        beta.kubernetes.io/arch: amd64
      tolerations:
        - effect: NoSchedule
          key: node-restriction.kubernetes.io/workloads
          operator: Equal
          value: solrclouds
      resources:
        limits:
          memory: "1G"
        requests:
          cpu: "65m"
          memory: "156Mi"
  zookeeperRef:
    provided:
      zookeeper:
        persistence:
          spec:
            storageClassName: "hostpath"
            resources:
              requests:
                storage: "5Gi"
        replicas: 1
        zookeeperPodPolicy:
          resources:
            limits:
              memory: "1G"
            requests:
              cpu: "65m"
              memory: "156Mi"
