
apiVersion: v1
type: application
name: solr-operator
description: The Solr Operator enables easy management of Solr resources within Kubernetes.
version: 0.2.5
appVersion: v0.2.5
kubeVersion: ">= 1.13.0"
home: https://github.com/bloomberg/solr-operator
sources:
  - https://github.com/bloomberg/solr-operator
keywords:
  - solr
  - apache
  - search
  - lucene
  - operator
maintainers:
  - name: Houston Putman
    email: houston@apache.org
icon: https://lucene.apache.org/theme/images/solr/identity/Solr_Logo_on_white.png
