
apiVersion: v1
name: solr-operator
description: The Solr Operator enables easy management of Solr resources within Kubernetes.
version: 0.2.8
appVersion: v0.2.8
kubeVersion: ">= 1.16.0-0"
home: https://github.com/apache/lucene-solr-operator
sources:
  - https://github.com/apache/lucene-solr-operator
keywords:
  - solr
  - apache
  - search
  - lucene
  - operator
maintainers:
  - name: Houston Putman
    email: houston@apache.org
  - name: Balaji Sankaranarayanan
    email: bsankaranara@bloomberg.net
icon: https://lucene.apache.org/theme/images/solr/identity/Solr_Logo_on_white.png
