# Default values for solr-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: bloomberg/solr-operator
  tag: v0.2.0
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""


zkOperator: "true"
etcOperator: "true"
ingressBaseDomain: ing.local.domain

resources:
  limits:
    cpu: 400m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 100Mi