language: go
services:
  - docker

go:
  - "1.15"
  - master

script:
  - docker --version
  - make clean
  - ./hack/install_dependencies.sh

  # build locally and test generated files and code
  - make mod-tidy
  - make manifests
  - make build

  - make manifests-check
  - make test

jobs:
  include:
    - stage: "Docker"
      name: "Build (& Release if tagged)"
      script:
        - make docker-vendor-build
      deploy:
        - provider: script
          script: bash docker_deploy.sh
          skip_cleanup: true
          on:
            tags: true
            condition: -n "$DOCKER_PASSWORD"
