---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr-operator 
  labels:
    control-plane: solr-operator
spec:
  selector:
    matchLabels:
      control-plane: solr-operator 
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: solr-operator 
    spec:
      containers:
      - args:
        - -zk-operator=true
        - -etcd-operator=false
        - -ingress-base-domain=ing.local.domain
        image: controller:0.1.5-2
        imagePullPolicy: Always
        name: solr-operator
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SECRET_NAME
            value: webhook-server-secret 
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
