
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: solr-operator-role
rules:
- resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - configmaps/status
  verbs:
  - get
  - patch
  - update
- resources:
  - pods
  verbs:
  - get
  - list
  - watch
- resources:
  - pods/exec
  verbs:
  - create
- resources:
  - pods/status
  verbs:
  - get
- resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - etcdclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - etcdclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - solr.bloomberg.com
  resources:
  - solrbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - solr.bloomberg.com
  resources:
  - solrbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - solr.bloomberg.com
  resources:
  - solrclouds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - solr.bloomberg.com
  resources:
  - solrclouds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - solr.bloomberg.com
  resources:
  - solrcollections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - solr.bloomberg.com
  resources:
  - solrcollections/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - solr.bloomberg.com
  resources:
  - solrprometheusexporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - solr.bloomberg.com
  resources:
  - solrprometheusexporters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - zookeeper.pravega.io
  resources:
  - zookeeperclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zookeeper.pravega.io
  resources:
  - zookeeperclusters/status
  verbs:
  - get
  - patch
  - update
