{{- if .Values.rbac.create }}
{{- range $namespace := (split "," (include "solr-operator.watchNamespaces" $)) }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "solr-operator.roleType" $ }}
metadata:
  creationTimestamp: null
  name: {{ include "solr-operator.fullname" $ }}-role
  namespace: {{ $namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - solr.apache.org
  resources:
  - solrbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - solr.apache.org
  resources:
  - solrbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - solr.apache.org
  resources:
  - solrcloud
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - solr.apache.org
  resources:
  - solrcloud/status
  verbs:
  - get
- apiGroups:
  - solr.apache.org
  resources:
  - solrclouds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - solr.apache.org
  resources:
  - solrclouds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - solr.apache.org
  resources:
  - solrcollectionaliases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - solr.apache.org
  resources:
  - solrcollectionaliases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - solr.apache.org
  resources:
  - solrcollections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - solr.apache.org
  resources:
  - solrcollections/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - solr.apache.org
  resources:
  - solrprometheusexporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - solr.apache.org
  resources:
  - solrprometheusexporters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - zookeeper.pravega.io
  resources:
  - zookeeperclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zookeeper.pravega.io
  resources:
  - zookeeperclusters/status
  verbs:
  - get
  - patch
  - update

{{- end }}
{{- end }}
