name: Docker Build

on:
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    name: Build Docker Image

    runs-on: ubuntu-latest

    steps:
      # Setup
      - uses: actions/checkout@v2

      # Cleanup & Install dependencies
      - run: docker --version
      - run: make docker-build